### ISSUE TITLE
Create Action, State and Reducer classes

### ISSUE THREAD

**Issue by raulccabreu** [raulccabreu/redukt#3]

**Comment by flaviokreis** [comment]
We can split this story.

**Comment by raulccabreu** [comment]
I agree...maybe:
1. State and Action models (simple classes)
2. Reducers
3. Dispatcher related classes (dispatcher loop)

What you think? @flaviokreis @niltonvasques

**Comment by flaviokreis** [comment]
For me It is ok.

**Comment by raulccabreu** [comment]
I'm think that item 1 and 2 can go together: State, Action and Reducer (state and action are very simple and alone they are useless). So we can edit this issue here to be item 1 and create a new issue to item 2, ok?
